# Generated by Django 4.2.1 on 2024-04-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredusers',
            name='Phone_No',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
