# Generated by Django 4.2.1 on 2024-04-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_registeredusers_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Aadhar_Back',
            field=models.ImageField(default='', upload_to='aadharback'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Aadhar_Front',
            field=models.ImageField(default='', upload_to='aadharfront'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Profile_Picture',
            field=models.ImageField(default='abc.png', upload_to='profile'),
        ),
        migrations.AlterField(
            model_name='employee_to_employer_call',
            name='Photo_Url',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='employee_to_employer_job',
            name='Photo_Url',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='employer_to_employee_call',
            name='Photo_Url',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='employer_to_employee_job',
            name='Photo_Url',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='job',
            name='Job_Image',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='jobcategory',
            name='Photo',
            field=models.TextField(default='others.png'),
        ),
    ]
