# Generated by Django 4.2.1 on 2024-04-24 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_employee_aadhar_back_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_to_employer_job',
            name='Job_Shift',
            field=models.CharField(default='Day', max_length=200),
        ),
        migrations.AddField(
            model_name='job',
            name='Job_Shift',
            field=models.CharField(default='Day', max_length=200),
        ),
    ]
