# Generated by Django 4.2.1 on 2024-05-17 11:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_employee_to_employer_job_job_shift_job_job_shift'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppNotification',
            fields=[
                ('Notification_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Notification_Title', models.TextField()),
                ('Notification_Message', models.TextField()),
                ('Notification_Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='Validity',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='Validity',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
