# Generated by Django 4.2.1 on 2024-05-22 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_appnotification_alter_employee_validity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='Email_ID',
            field=models.CharField(blank=True, default='-', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='Organization',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='Organization_Type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='Referred_By',
            field=models.CharField(blank=True, default='-', max_length=100, null=True),
        ),
    ]
