# Generated by Django 4.2.1 on 2024-05-24 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_employer_email_id_alter_employer_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appnotification',
            name='Type',
            field=models.CharField(choices=[('EE', 'Employee'), ('ER', 'Employer')], default='EE', max_length=2),
        ),
    ]
