# Generated by Django 4.2.1 on 2024-06-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_employeequalification_options_job_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer_to_employee_job',
            name='Job_Shift',
            field=models.CharField(default='Day', max_length=200),
        ),
    ]
